###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deblurring'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 13
  NUM_EPOCHS: 100
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-5
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: True
  TRAIN_PS: 64
  VAL_PS: 64
#  TRAIN_DIR: 'D:\myprojs\data\GOPRO_Large\GOPRO_train256_4x_HDF5\LR-GOPRO_x4_Part1.h5' # path to training data
  TRAIN_DIR: 'D:\myprojs\data\GOPRO_Large\train_all\aug' # path to training data
  VAL_DIR: 'D:\myprojs\data\GOPRO_Large\test_all'    # path to validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  # SAVE_IMAGES: False
